### ISSUE TITLE
No support for 20pt @1x @2x & @3x

### ISSUE THREAD

**Issue by elichamberlin** [jtholloran/icons#1]
for iPhone and iPad notification

**Comment by jtholloran** [comment]
Thanks @elichamberlin. Added these sizes to v1.1.

**Comment by staticdreams** [comment]
How come latest commit removes 20pt icons? As far as I see in Xcode 9.2 we still have notifications icons size at 20pt 1x 2x 3x..

**Comment by jtholloran** [comment]
Hey @staticdreams, these sizes have been added back to v1.2.1. You can read the release notes wrt what happened there. Thanks.
