### ISSUE TITLE
Match official required icon sizes and naming

### ISSUE THREAD

**Issue by maggo** [jtholloran/icons#6]
Hi! First off all, thank you very much for this sketch file, helped us immensely and the exports looks so much better than what the resizing tools out there tend to produce.

I realised that you're exporting 20x20 icons but they don't seem to be required anymore, see https://developer.apple.com/library/content/qa/qa1686/_index.html

Also it would be nice if the export names matched the recommended filenames. That would make it easier to replace the icons in Cordova and other tools. You can find them under the apple link section "Icons for Universal Applications"

Cheers

**Comment by jtholloran** [comment]
Thanks! These have been addressed with v1.2.
