### ISSUE TITLE
Does not support text

### ISSUE THREAD

**Issue by bhagyas** [jtholloran/icons#7]

**Comment by jtholloran** [comment]
@bhagyas Can you elaborate? Are you referring to text being scalable...in which case, are you using Sketch 48 that introduces scalable symbols?

**Comment by bhagyas** [comment]
Yes. The text don't get scaled when included in the icon images. 

On 47, not 48.

**Comment by jtholloran** [comment]
Yep, I'd recommend updating to 48. In previous versions of Sketch, you'll need to outline the text (Cmd + Shift + O) and flatten any artwork contained in the symbol.

**Comment by bhagyas** [comment]
Yes,  I guess that should work, thank you.
